// chapter 9 Start //
// Q1
// var A =prompt("Entey your City");
// alert("“Welcome to city of lights”");
// chapter 9 Com //

// chapter 10 Start //

// var userGender = prompt("Enter your gender");

// if (userGender === "Male"){
//   alert ("Good Mornimg Sir...");
// }
// else {
//     alert("Good Mornimg Mam...");
//   }
// chapter 11 start //
// Q1

// chapter 11 com //

// Chapter 12 start //
// Q1
// var full = +prompt("Enter full");

// if (full <= 0.25) {
//   alert("“Please refill the fuel in your car”");
// }
// else {
//     alert("Good job")
// }
// chapter 13
// Q1
// var x = prompt("Where does the Pope live?");
// if (x === "Karachi") {
//   alert("Correct!");
// } else if (x !== "lahore , Islamabad") {
//   alert("Wrong answer");
// }
// // Q2
// var b = prompt("What Do you Answer", 82);
// if (b++ === 83) {
//   alert("Corret Ans");
// } else {
//   alert("Not Corret Ans");
// }
// Q3
// Singup//
// var name = prompt("Enter your name")
// var email = prompt("Enter your Email")
// var pass = prompt("Enter your pass")

// // Login //
//  var emaillog =prompt ("Enter your Email")
//  var passlog =  prompt("Enter your pass")

// if ((email==emaillog) && (pass ==passlog) ){
//    document.write("Welcome to user" +"<br>")
//    let eng= parseFloat(prompt("Enter your English Mark"))
//    let urdu= parseFloat(prompt("Enter your urdu Mark"))
//    let Math= parseFloat(prompt("Enter your Math Mark"))
//     let obtained = eng+urdu+Math;
//     let perc=(obtained/300)*1000
//     document.write("Obtained"+obtained +"<br>")
//     document.write("percentage"+perc+"%"+ "<br>")
//     if(pres<=100 && pres>=80){
//       docoment.write("Grade Is A+")
//     }
//     else  if(pres<=80 && pres>=70){
//       docoment.write("Grade Is A")
//     }
//     else if(pres<=70 && pres>=60){
//       docoment.write("Grade Is B")

//     }
//     else  if(pres<=60 && pres>=50){
//       docoment.write("Grade Is C")
//     }else{
//       document.write("Fail")
//     }

// }
// else{
//   document.write("Invalid Email or password")
// }



// pdf 2 //
// var name = prompt("Enter your name ")
// if("name === ubaid"){
//   alert("Welcome to Ubaid")
// }
// else if ("") {
//   alert("d;krorrgrgj");
// }
// // Q2
//   var passlog =  prompt("Enter your pass")
//   var pass = prompt("Enter your pass")
//   if("pass === passlog"){
//     alert("Good job")
//   }
// else if(pass === passlog){
//   alert("vjrgoirehjjGood job")

// }
// q3
var num1 = +prompt("Enter your Whether number")
if(num1 === "<=35"){
      alert("cold")

}
else if (">=40"){
  alert("summer")
  
}
// Q4
var greeting = ;
var hour = 13;
if (hour < 18) {
greeting = "Good day";}
 else{
   alert("Good evening");
  
 }